services:
  - type: web
    name: bookseller-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn base.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
