# Generated by Django 5.0.7 on 2025-04-20 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_usershippingaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
