# Generated by Django 5.0.7 on 2025-04-20 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_classfilter'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
